server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: mypass
    url: "jdbc:postgresql://localhost:5332/cars"
    username: myuser
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true